### ISSUE TITLE
xml:id should be unique value

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-nor#2]
I just noticed you have two texts with the same value for `TEI/@xml:id`:
~~~~
 ELTEC_BS_Kielland_GarmanOgWorse_tekst.xml:<TEI xml:id="NOR0002" xml:lang="nb" xmlns="http://www.tei-c.org/ns/1.0">
ELTEC_Skram_Forraadt_tekst.xml:<TEI xml:id="NOR0002" xml:lang="nb" xmlns="http://www.tei-c.org/ns/1.0">
~~~~
Please fix!

**Comment by michaelprem** [comment]
First thing in the morning 😃

Sendt fra min Huawei-mobiltelefon

-------- Opprinnelig melding --------
Emne: [COST-ELTeC/ELTeC-nor] xml:id should be unique value (#2)
Fra: Lou
Til: COST-ELTeC/ELTeC-nor
Kopi: Subscribed


I just noticed you have two texts with the same value for TEI/@xml<https://github.com/xml>🆔
ELTEC_BS_Kielland_GarmanOgWorse_tekst.xml:
ELTEC_Skram_Forraadt_tekst.xml:

Please fix!
